#!/bin/bash

# Release build for Windows x86_64 platform

set -e

BUILD_DIR="./build-release/win"
RELEASE_DIR="./releases"
TOOLCHAIN="./cmake/mingw-w64-x86_64.cmake"
SHA_FILE="SHA256"

cmake -B $BUILD_DIR -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN
cmake --build $BUILD_DIR
cpack --config $BUILD_DIR/CPackConfig.cmake -B releases
cd $RELEASE_DIR && sha256sum simple_platformer_demo* > $SHA_FILE
cat $SHA_FILE
